version: "3.8"

services:
  frontend:
    build: ./client
    ports:
      - "5173:80"
    env_file: ./client/.env
    depends_on:
      - backend
    networks:
      - mern-app

  backend:
    build: ./server
    ports:
      - "3000:3000"
    env_file: ./server/.env
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://root:changeme@mongo:27017/Factchecker?authSource=admin"
    networks:
      - mern-app

  mongo:
    image: mongo:7.0.12
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "changeme"

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
    - 8085:8081
    networks:
      - mern-app
    environment:
      # Mongo Express UI Credentials
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "pass"

      # Mongo DB Credentials
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "changeme"
      ME_CONFIG_MONGODB_URL: "mongodb://root:changeme@mongo:27017/"

volumes:
  mongo_data:
networks:
  mern-app:
    driver: bridge
